// Generated by scripts/build-content.mjs from content/source/.
// Do not edit by hand. Edit the markdown and run: npm run content
import type { LegalDoc } from './types';

export const legalDocs: Record<string, LegalDoc> = {
  "privacy": {
    "slug": "privacy",
    "title": "Privacy notice",
    "effective": "April 19th, 2019",
    "revised": "August 9th, 2022",
    "sections": [
      {
        "heading": "1. INTRODUCTION",
        "blocks": [
          {
            "type": "p",
            "text": "This privacy notice provides you with details of how we collect and process your personal data.",
            "links": []
          },
          {
            "type": "p",
            "text": "DATA DIGGERS MARKET RESEARCH SRL, is a Romanian company with the head office in Union Building, 6th floor, 11 Ion Campineanu Street district 1, Romania (hereinafter “DataDiggers“, “We“ of the “Company“) is a fieldwork expert who offers a web platform which provides solutions and flawless supporting services to market researcher s across the globe.",
            "links": []
          },
          {
            "type": "p",
            "text": "By registering on our platform you become a member and will provide some personal data to us. The membership with our platforms makes you eligible for participating in opinion surveys at the request of our clients and if you desire so.",
            "links": []
          },
          {
            "type": "p",
            "text": "The postal address of our Data Protection Officer is Union Building, 6th floor, 11 Ion Campineanu Street district 1, Romania.",
            "links": []
          },
          {
            "type": "p",
            "text": "If you are not happy with any aspect of how we collect and use your data, you have the right to complain to the ANSPDCP, the Romanian supervisory authority for data protection issues (www.dataprotection.ro). We would be grateful if you would contact us first if you do have a complaint so that we can try to resolve it for you.",
            "links": [
              {
                "label": "(www.dataprotection.ro)",
                "href": "http://www.dataprotection.ro/"
              }
            ]
          },
          {
            "type": "p",
            "text": "It is very important that the information we hold about you is accurate and up to date. Please let us know if at any time your personal information changes by emailing us at membersupport@myvoice-surveys.com.",
            "links": [
              {
                "label": "membersupport@myvoice-surveys.com.",
                "href": "mailto:membersupport@myvoice-surveys.com."
              }
            ]
          },
          {
            "type": "p",
            "text": "We require your explicit consent for processing sensitive data.",
            "links": []
          }
        ],
        "id": "1-introduction"
      },
      {
        "heading": "2. HOW WE USE YOUR PERSONAL DATA",
        "blocks": [
          {
            "type": "p",
            "text": "We will only use your personal data when legally permitted. The most common uses of your personal data are:",
            "links": []
          },
          {
            "type": "p",
            "text": "1. Where we need to perform the relation between us (becoming a member of our platform, participating with the opinion surveys and sharing you data with beneficiaries of the opinion surveys).",
            "links": []
          },
          {
            "type": "p",
            "text": "2. Where it is necessary for our legitimate interests (or those of a third party) and your interests and fundamental rights do not override those interests.",
            "links": []
          },
          {
            "type": "p",
            "text": "3. Where we need to comply with a legal or regulatory obligation.",
            "links": []
          },
          {
            "type": "p",
            "text": "Generally, we do not rely on consent as a legal ground for processing your personal data. It is of the essence of our collaboration that subscribing to our panel we should be allowed to process your Data. It is possible that sometimes you provide us with Sensitive Data about you. Sensitive data refers to data that includes details about your race or ethnicity, religious or philosophical beliefs, sex life, sexual orientation, political opinions, trade union membership, information about your health and genetic and bio-metric data (e.g. eye tracking, facial coding). The reason you may choose proving us with any of the above information is your consent to include you in a wider range of opinion surveys and in order for you to generate higher incomes. We do not collect any information about criminal convictions and offences. When processing you sensitive Data, we will rely on your consent.",
            "links": []
          },
          {
            "type": "p",
            "text": "You have the right to opt-out any time from our collaboration or only to withdraw you consent for processing you sensitive Data by emailing us at membersupport@myvoice-surveys.com.",
            "links": [
              {
                "label": "membersupport@myvoice-surveys.com.",
                "href": "mailto:membersupport@myvoice-surveys.com."
              }
            ]
          },
          {
            "type": "p",
            "text": "Purposes for processing your personal data",
            "links": []
          },
          {
            "type": "p",
            "text": "The set out below is a description of the ways we intend to use your personal data and the legal grounds on which we will process such data. We have also explained what our legitimate interests are where relevant.",
            "links": []
          },
          {
            "type": "p",
            "text": "We may process your personal data for more than one lawful ground, depending on the specific purpose for which we are using your data. Please email us at membersupport@myvoice-surveys.com if you need details about the specific legal ground we are relying on to process your personal data where more than one ground has been set out in the table below.",
            "links": [
              {
                "label": "membersupport@myvoice-surveys.com",
                "href": "mailto:membersupport@myvoice-surveys.com"
              }
            ]
          },
          {
            "type": "p",
            "text": "Email communication",
            "links": []
          },
          {
            "type": "p",
            "text": "You will receive email communications from us:",
            "links": []
          },
          {
            "type": "p",
            "text": "(i)When we invite you to participate in a survey;",
            "links": []
          },
          {
            "type": "p",
            "text": "(ii)When we provide you relevant information regarding the functioning of our platform (e.g. public holidays, changes without terms and conditions, payments related information etc.).",
            "links": []
          },
          {
            "type": "p",
            "text": "We will get your express opt-in consent before we start sending you marketing emails (other than info relevant and based on our collaborations) or before share your personal data with any third party for marketing purposes.",
            "links": []
          },
          {
            "type": "table",
            "head": [
              "Purpose/Activity",
              "Type of data",
              "Lawful basis for processing"
            ],
            "rows": [
              [
                "To register you as a new member of our platform",
                "(a) Age (b) sex (c) location (d) email",
                "Performance of the relation with you – registering as a member of our platform."
              ],
              [
                "To process and deliver your incentives: (a) Manage payments, fees and charges",
                "(a) Identity (b) Contact (c) Financial (d) Transaction",
                "(a) Performance of the relation with you (b) Necessary for our legitimate interests to recover payments performed to you in lack of a grounded reason"
              ],
              [
                "To manage our relationship with you which will include: (a) Notifying you about changes to our terms or privacy policy (b) Asking you to leave a review or take a survey",
                "(a) Identity (b) Contact (c) Profile (d) Marketing and Communications",
                "(a) Performance of the relation with you (b) Necessary to comply with a legal obligation (c) Necessary for our legitimate interests to keep our records updated and to study how customers use our products/services"
              ],
              [
                "To administer and protect our business and our site (including troubleshooting, data analysis, testing, system maintenance, support, reporting and hosting of data)",
                "(a) Identity (b) Contact (c) Technical",
                "(a) Necessary for our legitimate interests for running our business, provision of administration and IT services, network security, to prevent fraud and in the context of a business reorganization or group restructuring exercise (b) Necessary to comply with a legal obligation"
              ],
              [
                "To use data analytics to improve our website, products/services, marketing, customer relationships and experiences",
                "(a) Technical (b) Usage",
                "Necessary for our legitimate interests to define types of customers for our products and services, to keep our site updated and relevant, to develop our business and to inform our marketing strategy"
              ],
              [
                "To make suggestions and recommendations to you about goods or services that may be of interest to you",
                "(a) Identity (b) Contact (c) Technical (d) Usage (e) Profile",
                "Necessary for our legitimate interests to develop our products/services and grow our business"
              ],
              [
                "To share your contact details with our contractors in order for you to participate in poll directly with our contractors",
                "(a) Contact",
                "Necessary for your participation in polls with our contractors directly"
              ]
            ]
          }
        ],
        "id": "2-how-we-use-your-personal-data"
      },
      {
        "heading": "3. DISCLOSURES OF YOUR PERSONAL DATA",
        "blocks": [
          {
            "type": "p",
            "text": "We may have to share your personal data with the parties set out below for the purposes set out in the table in paragraph 2 above:",
            "links": []
          },
          {
            "type": "p",
            "text": "1. Service providers who provide IT and system administration services.",
            "links": []
          },
          {
            "type": "p",
            "text": "2. Professional advisers including lawyers, bankers, auditors and insurers who provide consultancy, banking, insurance and accounting services.",
            "links": []
          },
          {
            "type": "p",
            "text": "3. HM Revenue & Customs, regulators and other authorities based in Romania and other relevant jurisdictions who require reporting of processing activities in certain circumstances.",
            "links": []
          },
          {
            "type": "p",
            "text": "4. Third parties to whom we sell, transfer, or merge parts of our business or our assets, or to contractors for your participation in detailed surveys.",
            "links": []
          },
          {
            "type": "p",
            "text": "We require all third parties to whom we transfer your data to respect the security of your personal data and to treat it in accordance with the law. We only allow such third parties to process your personal data for specified purposes and in accordance with our instructions.",
            "links": []
          },
          {
            "type": "p",
            "text": "When participating to certain surveys, you may be asked if you want your email address is shared with the beneficiaries of the surveys in order for you to participate to next stages of the surveys. We will share your email address only if you consent to such actions.",
            "links": []
          }
        ],
        "id": "3-disclosures-of-your-personal-data"
      },
      {
        "heading": "4. INTERNATIONAL TRANSFERS",
        "blocks": [
          {
            "type": "p",
            "text": "We share your personal data within a group of companies which involves transferring your data outside the European Economic Area (EEA).",
            "links": []
          },
          {
            "type": "p",
            "text": "Countries outside of the European Economic Area (EEA) do not always offer the same levels of protection to your personal data, so European law has prohibited transfers of personal data outside of the EEA unless the transfer meets certain criteria.",
            "links": []
          },
          {
            "type": "p",
            "text": "Many of our third parties service providers are based outside the European Economic Area (EEA) so their processing of your personal data will involve a transfer of data outside the EEA.",
            "links": []
          },
          {
            "type": "p",
            "text": "Whenever we transfer your personal data out of the EEA, we do our best to ensure a similar degree of security of data by ensuring at least one of the following safeguards is implemented:",
            "links": []
          },
          {
            "type": "p",
            "text": "1. We will only transfer your personal data to countries that have been deemed to provide an adequate level of protection for personal data by the European Commission; or",
            "links": []
          },
          {
            "type": "p",
            "text": "2. Where we use certain service providers, we may use specific contracts or codes of conduct or certification mechanisms approved by the European Commission which give personal data the same protection it has in Europe; or",
            "links": []
          },
          {
            "type": "p",
            "text": "3. Where we use providers based in the United States, we may transfer data to them if they are part of the EU-US Privacy Shield, which requires them to provide similar protection to personal data shared between the Europe and the US.",
            "links": []
          },
          {
            "type": "p",
            "text": "If none of the above safeguards is available, we may request your explicit consent to the specific transfer. You will have the right to withdraw this consent at any time.",
            "links": []
          },
          {
            "type": "p",
            "text": "Please email us at membersupport@myvoice-surveys.com if you want further information on the specific mechanism used by us when transferring your personal data out of the EEA.",
            "links": [
              {
                "label": "membersupport@myvoice-surveys.com",
                "href": "mailto:membersupport@myvoice-surveys.com"
              }
            ]
          }
        ],
        "id": "4-international-transfers"
      },
      {
        "heading": "5. DATA SECURITY",
        "blocks": [
          {
            "type": "p",
            "text": "We have put in place appropriate security measures to prevent your personal data from being accidentally lost, used or accessed in an unauthorized way, altered or disclosed. In addition, we limit access to your personal data to those employees, agents, contractors and other third parties who have a business need to know such data. They will only process your personal data on our instructions and they are subject to a duty of confidentiality.",
            "links": []
          },
          {
            "type": "p",
            "text": "We have put in place procedures to deal with any suspected personal data breach and will notify you and any applicable regulator of a breach where we are legally required to do so.",
            "links": []
          }
        ],
        "id": "5-data-security"
      },
      {
        "heading": "6. DATA RETENTION",
        "blocks": [
          {
            "type": "p",
            "text": "We will only retain your personal data for as long as necessary to fulfill the purposes we collected it for, including for the purposes of satisfying any legal, accounting, or reporting requirements.",
            "links": []
          },
          {
            "type": "p",
            "text": "To determine the appropriate retention period for personal data, we consider the amount, nature, and sensitivity of the personal data, the potential risk of harm from unauthorized use or disclosure of your personal data, the purposes for which we process your personal data and whether we can achieve those purposes through other means, and the applicable legal requirements.",
            "links": []
          },
          {
            "type": "p",
            "text": "By law we have to keep basic information about our customers (including Contact, Identity, Financial and Transaction Data) for 10 years after they cease being customers for tax purposes.",
            "links": []
          },
          {
            "type": "p",
            "text": "In some circumstances you can ask us to delete your data: see below for further information.",
            "links": []
          },
          {
            "type": "p",
            "text": "In some circumstances we may anonymize your personal data (so that it can no longer be associated with you) for research or statistical purposes in which case we may use this information indefinitely without further notice to you.",
            "links": []
          }
        ],
        "id": "6-data-retention"
      },
      {
        "heading": "7. YOUR LEGAL RIGHTS",
        "blocks": [
          {
            "type": "p",
            "text": "Under certain circumstances, you have rights under data protection laws in relation to your personal data. These include the right to:",
            "links": []
          },
          {
            "type": "p",
            "text": "1. Request access to your personal data.",
            "links": []
          },
          {
            "type": "p",
            "text": "2. Request correction of your personal data.",
            "links": []
          },
          {
            "type": "p",
            "text": "3. Request erasure of your personal data.",
            "links": []
          },
          {
            "type": "p",
            "text": "4. Object to processing of your personal data.",
            "links": []
          },
          {
            "type": "p",
            "text": "5. Request restriction of processing your personal data.",
            "links": []
          },
          {
            "type": "p",
            "text": "6. Request transfer of your personal data.",
            "links": []
          },
          {
            "type": "p",
            "text": "7. Right to withdraw consent.",
            "links": []
          },
          {
            "type": "p",
            "text": "If you wish to exercise any of the rights set out above, please email us at membersupport@myvoice-surveys.com.",
            "links": [
              {
                "label": "membersupport@myvoice-surveys.com.",
                "href": "mailto:membersupport@myvoice-surveys.com."
              }
            ]
          },
          {
            "type": "p",
            "text": "You will not have to pay a fee to access your personal data (or to exercise any of the other rights). However, we may charge a reasonable fee if your request is clearly unfounded, repetitive or excessive. Alternatively, we may refuse to comply with your request in these circumstances.",
            "links": []
          },
          {
            "type": "p",
            "text": "We may need to request specific information from you to help us confirm your identity and ensure your right to access your personal data (or to exercise any of your other rights). This is a security measure to ensure that personal data is not disclosed to any person who has no right to receive it. We may also contact you to ask you for further information in relation to your request to speed up our response.",
            "links": []
          },
          {
            "type": "p",
            "text": "We try to respond to all legitimate requests within one month. Occasionally it may take us longer than a month if your request is particularly complex or you have made a number of requests. In this case, we will notify you and keep you updated.",
            "links": []
          }
        ],
        "id": "7-your-legal-rights"
      }
    ]
  },
  "cookies": {
    "slug": "cookies",
    "title": "Cookie policy",
    "effective": "April 19th, 2019",
    "revised": "August 9th, 2022",
    "sections": [
      {
        "heading": "What's a \"cookie\"?",
        "blocks": [
          {
            "type": "p",
            "text": "A \"cookie\" is a piece of information that is stored on your computer's hard drive and which records how you move your way around a website so that, when you revisit that website, it can present tailored options based on the information stored about your last visit. Cookies can also be used to analyze traffic and for advertising and marketing purposes.",
            "links": []
          },
          {
            "type": "p",
            "text": "Cookies are used by nearly all websites and do not harm your system.",
            "links": []
          },
          {
            "type": "p",
            "text": "If you want to check or change what types of cookies you accept, this can usually be altered within your browser settings. You can block cookies at any time by activating the setting on your browser that allows you to refuse the setting of all or some cookies. However, if you use your browser settings to block all cookies (including essential cookies) you may not be able to access all or parts of our site.",
            "links": []
          }
        ],
        "id": "what-s-a-cookie"
      },
      {
        "heading": "How do we use cookies?",
        "blocks": [
          {
            "type": "p",
            "text": "We use cookies to track your use of our website. This enables us to understand how you use the site and track any patterns with regards how you are using our website. This helps us to develop and improve our website as well as products and / or services in response to what you might need or want.",
            "links": []
          }
        ],
        "id": "how-do-we-use-cookies"
      },
      {
        "heading": "Cookies are either:",
        "blocks": [
          {
            "type": "list",
            "items": [
              "Session cookies: these are only stored on your computer during your web session and are automatically deleted when you close your browser – they usually store an anonymous session ID allowing you to browse a website without having to log in to each page but they do not collect any personal data from your computer; or",
              "Persistent cookies: a persistent cookie is stored as a file on your computer and it remains there when you close your web browser. The cookie can be read by the website that created it when you visit that website again. [We use persistent cookies for Google Analytics.]"
            ]
          }
        ],
        "id": "cookies-are-either"
      },
      {
        "heading": "Cookies can also be categorized as follows:",
        "blocks": [
          {
            "type": "list",
            "items": [
              "Strictly necessary cookies: These cookies are essential to enable you to use the website effectively, such as when buying a product and / or service, and therefore cannot be turned off. Without these cookies, the services available to you on our website cannot be provided. These cookies do not gather information about you that could be used for marketing or remembering where you have been on the Internet.",
              "Performance cookies: These cookies enable us to monitor and improve the performance of our website. For example, they allow us to count visits, identify traffic sources and see which parts of the site are most popular.",
              "Functionality cookies: These cookies allow our website to remember choices you make and provide enhanced features. For instance, we may be able to provide you with news or updates relevant to the services you use. They may also be used to provide services you have requested such as viewing a video or commenting on a blog. The information these cookies collect is usually anonymous."
            ]
          },
          {
            "type": "p",
            "text": "[Please note that third parties who advertise on our website (including, for example, advertising networks and providers of external services like web traffic analysis services) may also use cookies, over which we have no control. These cookies are likely to be analytical/performance cookies or targeting cookies]",
            "links": []
          }
        ],
        "id": "cookies-can-also-be-categorized-as-follows"
      }
    ]
  },
  "terms": {
    "slug": "terms",
    "title": "Terms and conditions for panel membership, survey participation and use of services",
    "effective": "April 19th, 2019",
    "revised": "April 18th, 2022",
    "sections": [
      {
        "heading": "Definitions",
        "blocks": [
          {
            "type": "p",
            "text": "When used in these Terms, the following terms and expressions shall have the following meanings.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Active Panelist” refers to a Panel Member that has: (a) participated in a Survey, (b) other Research Program; or (c) other parts of the Service, at least once over the last twelve (12) months; or (d) updated his/her profile or member information at least once in the last twelve (12) months.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Market Research Tracking Service” refers to a Service accepted by a User that may track online behavior of such User, such as websites accessed by the User and online campaigns exposed to the User for market research purposes, including advertising tracking research.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Applicable Law” refers to applicable national and/or local laws and regulations.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Client” refers to Our clients to whom We provide services.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Content” refers to the information on Our Site, a Survey Site, a Panel Site or a Partner Site.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Panel” refers to a group of individuals who have agreed to be invited to and participate in market research Surveys, other Research Programs or other parts of the Services for market research.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Panel Member” refers to a member of a Panel.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Panel Owner” refers to the owner of a Panel and a Panel Site that You are a Panel Member of. We may be a Panel Owner, as well as any of Our partners.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Panel Site” refers to a website where individuals can register to become Panel Members.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Partner” refers to one of Our partners, including Panel Owners and other partners.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Partner Site” refers to a website that is operated by one of our Partners.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Participant” refers to an individual, who is not a Panel Member, directed to a Survey, other Research Program or other parts of the Services by one of Our Partners.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Personal Data” means any information relating to an identified or identifiable natural person (“Data Subject”); an identifiable natural person is one who can be identified or traced, directly or indirectly, in particular by reference to an identifier either alone or when combined with other personal or identifying information. Personal Data can include information such as name, social security number, date and place of birth, mother‘s maiden name, biometric records, photographs, sound or video recording, and other information that is linked or linkable to an individual, such as medical, educational, financial, and employment information. (NOTE: Personal Data may also be referred to as Personally Identifiable Information or PII.)",
            "links": []
          },
          {
            "type": "p",
            "text": "“Research Program” refers to research opportunity other than a Survey.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Restricted Content” refers to confidential and/or proprietary information, materials, products, and Content belonging to Us and/or a Panel Owner, a Survey Owner, a Client, a Partner and/or a licensor.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Service” refers to the service provided by Us that permits You, as a Panel Member or a Participant, to participate in (a) a Panel or a Survey, (b) other research program, or (c) any other service provided by Us and used by You, such as a Market Research Tracking Service.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Submissions” refers to all comments, feedback, suggestions, ideas and other information that You submit or We collect when You participate in a Panel, respond to a Survey or other Research Program or use a Service.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Survey Owner” refers to the owner of a Survey, which typically is a Client.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Survey Site” refers to the website where You respond to and complete a Survey.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Surveys” refers to market research surveys made available by Us to You.",
            "links": []
          },
          {
            "type": "p",
            "text": "“Third Party Websites” refers to websites maintained and/or operated by third parties.",
            "links": []
          },
          {
            "type": "p",
            "text": "“User” refers to You as an individual when You use the Service.",
            "links": []
          },
          {
            "type": "p",
            "text": "“User Content” refers to all content, materials, information, and comments You use, upload, post or submit or We collect when You use the Service, including information received through Ad Tracking Service, such as Internet usage pattern data.",
            "links": []
          },
          {
            "type": "p",
            "text": "“You“, “Yourself“, “Your” and “Yours” refer to you as an individual.",
            "links": []
          },
          {
            "type": "p",
            "text": "“We“, “Us“, “Our” and “DataDiggers” refer to the Romanian company Data Diggers Market Research S.R.L., reg. no. J23/915/2015.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "definitions"
      },
      {
        "heading": "1. Applicability; Agreement",
        "blocks": [
          {
            "type": "p",
            "text": "These Terms and Conditions (hereinafter the “Terms”) apply in addition to any agreement with Panel Owner of the Panel of which you are a Panel Member, as well as any specific terms, which may apply for a Survey, other Research Program or other Service. These Terms shall not apply to the extent they are in conflict with the terms of an agreement between You and a Panel Owner or with specific terms provided by the Panel Owner or Client as a condition for Your participation in a Survey or other Research Program, provided, however, that such other terms shall not reduce Our rights or increase Our liability specified in these Terms.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "1-applicability-agreement"
      },
      {
        "heading": "2. Introduction",
        "blocks": [
          {
            "type": "p",
            "text": "The purpose of these Terms is to set out the general terms and conditions for Your use of the Services, including Your participation in Surveys, Panel or other Research Programs. We manage the relationship between a Survey Owner and a Panel Owner and We act on behalf of a Panel Owner. We are also the platform supplier, providing opportunities for Panel Members, to participate in Surveys, other Research Programs and use other services. In addition to the above, We may also manage incentives. Details regarding such incentive scheme can be found in these Terms.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "2-introduction"
      },
      {
        "heading": "3. Panel Membership Eligibility",
        "blocks": [
          {
            "type": "p",
            "text": "Panel membership is generally open to individuals who satisfy the requirements for membership, including, but not limited to, minimum age requirements and geographic location requirements. The requirements for Panel membership may vary by specific Panel and are determined by a Panel Owner. By agreeing to become a Panel Member, You agree to receive invitations to participate in Surveys, Research Programs or other Services, both from the Panel Owner you have applied to Panel membership for and from other Panel Owners. You may unsubscribe from Panel membership at any time, please see Section 12 “Opt-Out Policy” below. We only allow one Panel Member per unique email address within each Panel.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "3-panel-membership-eligibility"
      },
      {
        "heading": "4. Panel Registration",
        "blocks": [
          {
            "type": "p",
            "text": "In order to become a Panel Member, You must register with a Panel Site and provide certain information about Yourself. The information You provide must be true, correct and complete. We reserve the right to restrict or prohibit Your access to the Service or participation in a Survey or other Research Program if You provide information, or We have reason to suspect that the information You have provided is not true, correct and complete. A Panel membership is personal and may only be used by the individual who registers for membership with a Panel. You are responsible for keeping any user information and password confidential and You are responsible for any use, whether authorized or unauthorized, of Your membership account.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "4-panel-registration"
      },
      {
        "heading": "5. Conditions for Participation in a Survey, Other Research Program or Other Services",
        "blocks": [
          {
            "type": "p",
            "text": "When You participate in a Survey, other Research Program or other Service, and/or use Our Site, a Survey Site or a Panel Site, You are obligated to comply with these Terms, as well as any other terms and conditions that apply to Your participation, including any agreement between You and a Panel Owner or terms applied by a Client or a Partner.",
            "links": []
          },
          {
            "type": "p",
            "text": "By participating in a Survey, other Research Program or other Service, You agree to provide true, correct and complete information about Yourself. If You provide information, or We have reason to suspect that the information You have provided is not true, correct and complete, You may not qualify for a Survey, other Research Program or other Service and consequently will not receive any incentives for Your participation. Furthermore, a Panel Owner may terminate Your membership with the result that You will not be able to participate in any more Surveys or other Research Programs. You are responsible for actions and communications undertaken or transmitted from Your account.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "5-conditions-for-participation-in-a-survey-other-r"
      },
      {
        "heading": "6. Use of the Services",
        "blocks": [
          {
            "type": "p",
            "text": "Participation in a Survey, other Research Service or use of other Service is voluntary. The Services are for personal and non-commercial use and We reserve the right to change, modify, restrict or block access to, all or any part of the Services, without prior notice. We may offer You any Service at any time if We believe it represents a viable opportunity for You to earn incentives by completing Surveys. We may at any time refuse to provide the Services to anyone at Our own discretion. You acknowledge that You are accessing, using, and/or participating in the Services in the capacity of an independent contractor, and no agency, partnership, joint-venture, employee-employer or franchisor-franchisee relationship is intended or created by these Terms.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "6-use-of-the-services"
      },
      {
        "heading": "7. Unauthorized Use",
        "blocks": [
          {
            "type": "p",
            "text": "You agree not to:",
            "links": []
          },
          {
            "type": "p",
            "text": "(a) disrupt, interfere with the security of or otherwise abuse the Service or Our Site, a Survey Site, a Panel Site, a Partner Site, or any services, system resources, accounts, servers or networks connected to or accessible through a Survey or a Survey Site or affiliated or linked sites;",
            "links": []
          },
          {
            "type": "p",
            "text": "(b) use spiders, robots or other automated data mining techniques to catalog, download, store, or otherwise reproduce or distribute data or content available in connection with the Service, or in other ways manipulate the result of a Survey;",
            "links": []
          },
          {
            "type": "p",
            "text": "(c) take any action to interfere with Our Site, a Survey Site, a Panel Site, or a Partner Site or an individual’s use of such sites, including, but not limited to, overloading, or “crashing” a website;",
            "links": []
          },
          {
            "type": "p",
            "text": "(d) send or transmit any viruses, corrupted data, or any other harmful, disruptive, or destructive code, file, or information, including, but not limited to, spyware, malware and trojans;",
            "links": []
          },
          {
            "type": "p",
            "text": "(e) collect any Personal Data of other Users of the Services;",
            "links": []
          },
          {
            "type": "p",
            "text": "(f) send unsolicited emails, such as promotions and advertisements for products or services;",
            "links": []
          },
          {
            "type": "p",
            "text": "(g) open, use, or maintain more than one (1) membership account with a Panel;",
            "links": []
          },
          {
            "type": "p",
            "text": "(h) use or attempt to use another User’s account, without authorization, or create an account with a false identity;",
            "links": []
          },
          {
            "type": "p",
            "text": "(i) attempt to obtain unauthorized access to Our Site, a Survey, a Survey Site, a Panel Site, a Partner Site or parts of a Survey, Our Site, a Survey Site, a Panel Site or a Partner Site that are restricted from general access;",
            "links": []
          },
          {
            "type": "p",
            "text": "(j) forge or mask Your true identity;",
            "links": []
          },
          {
            "type": "p",
            "text": "(k) frame a portion(s) of Our Site, a Survey Site, a Panel Site or a Partner Site and display it on another website or media or alter the appearance of any Survey Site, Panel Site, or Partner Site;",
            "links": []
          },
          {
            "type": "p",
            "text": "(l) establish links from a website to Our Site, a Survey Site, a Panel Site or a Partner Site or to the Services, without Our prior written consent;",
            "links": []
          },
          {
            "type": "p",
            "text": "(m) post or transmit any threatening, libelous, defamatory, obscene, pornographic, lewd, scandalous, or inflammatory material or content;",
            "links": []
          },
          {
            "type": "p",
            "text": "(n) use any foul; abusive or obscene language on Our Site, in a Survey or on a Survey Site, a Panel Site or a Partner Site;",
            "links": []
          },
          {
            "type": "p",
            "text": "(o) engage in any fraudulent activity, including, but not limited to, speeding through Surveys, taking the same Survey more than once, submitting false information during the registration process, submitting false or untrue Survey data, redeeming or attempting to redeem incentives through false or fraudulent means, tampering with Surveys and, with respect to the use of the Ad Tracking Service, accessing websites or online campaigns with the sole intention to provide a misrepresentative impression of Your online behavior;",
            "links": []
          },
          {
            "type": "p",
            "text": "(p) reverse engineer any aspect of a Service or take any acts that might reveal or disclose the source code, or bypass or circumvent measures or controls utilized to prohibit, restrict or limit access to any webpage, content or codes, except as expressly permitted by Applicable Law;",
            "links": []
          },
          {
            "type": "p",
            "text": "(q) engage in any criminal or illegal act(s) which may be linked to Our Site, a Survey or a Survey Site, a Panel Site or a Partner Site;",
            "links": []
          },
          {
            "type": "p",
            "text": "(r) use Restricted Content in violation or breach of these Terms; or",
            "links": []
          },
          {
            "type": "p",
            "text": "(s) encourage and/or advise any individual, including, but not limited to, Panel Members, Participants or any of Our employees, to commit an act in conflict with the Terms.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "7-unauthorized-use"
      },
      {
        "heading": "8. Restricted Content",
        "blocks": [
          {
            "type": "p",
            "text": "Unless otherwise noted, all materials, including, without limitation, all concepts, text, designs, graphics, drawings, photographs, video clips, music and sounds, and all trademarks, service marks and trade names used in a Survey, other Research Program or other Service and/or on Our site, a Survey Site, a Panel Site or a Partner Site and the selection and arrangements thereof, are subject to intellectual property rights, including but not limited to copyrights, trademarks and patents or the right to apply for their registration anywhere in the world, held by or licensed by Us, a Survey Owner, a Panel Owner, a Partner, or other third parties who are the respective owner of, or controls, such Restricted Content.",
            "links": []
          },
          {
            "type": "p",
            "text": "When You use a Service or participate in a Survey, other Research Program or other Service, You may be exposed to Restricted Content. You are not granted any rights to the Restricted Content and all intellectual property rights are expressly reserved. No license to use, reveal, download, copy, distribute, or reproduce (including but not limited to posting to any website, social media or blog) the Restricted Content or the subject matter of the Restricted Content is granted to You. Please be advised that legal action may be taken in the event any unauthorized use of the Restricted Content is traced back to You. You are hereby informed and acknowledge that We will fully cooperate with all third party requests for disclosures (including but not limited to the disclosure of Your identity) related to claims that You have used Restricted Content in violation of these Terms which We deem are legitimate. You may only participate in a Survey, other Research Program, other Service and/or use Our Site, a Survey Site, a Panel Site, or a Partner Site in a manner that does not infringe on Our, or a third party’s, intellectual property rights.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "8-restricted-content"
      },
      {
        "heading": "9. User Content",
        "blocks": [
          {
            "type": "p",
            "text": "You are responsible for all User Content. You are also responsible to obtain, where relevant, third party’s approvals, consents, and/or authorizations for Your and Our use of Your User Content. User Content, including photographs, sound or video recordings may be considered to be Personal Data. Your User Content may become publicly available and shared with third parties including, but not limited to, Our Clients, clients of Our Clients, Survey Owners, Panel Owners, Partners and third party service providers. You shall ensure that User Content does not contain copyrighted or trademarked content or material of any third party, including audio, video, images, or the likeness of anyone other than You, unless You have procured the approvals, consents and/or authorizations from such third parties required for Your and Our use of such User Content. You will not receive compensation for Our, Our Partners’ or Our Clients’ use of any User Content.",
            "links": []
          },
          {
            "type": "p",
            "text": "By using, uploading, posting, submitting or permitting Us to collect (such permission deemed granted upon Your consent with these Terms and use of the relevant Service) User Content in connection with the Services, You hereby grant to Us a perpetual, irrevocable, unlimited, transferrable, sub-licensable, world-wide, royalty free, right and license to edit, copy, transmit, publish, display, create derivative works of, reproduce, modify, distribute, and otherwise use Your User Content at Our own discretion. You will not receive any compensation for Your User Content or Our use of it, except where expressly agreed.",
            "links": []
          },
          {
            "type": "p",
            "text": "You are solely responsible to ensure that Your User Content, and Our use of it according to these Terms, will not infringe any third parties’ intellectual property rights. We do not and cannot review all User Content and We accept no liability whatsoever for Your User Content. We have the right, but not an obligation, to delete, remove, or edit Your User Content, which We, at Our sole discretion, deem to: (a) violate these Terms; (b) violate intellectual property rights; or (c) be abusive, defamatory, obscene, or otherwise unacceptable.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "9-user-content"
      },
      {
        "heading": "10. Policy on Points-Based Incentive Programs",
        "blocks": [
          {
            "type": "p",
            "text": "If You respond to and successfully complete a Survey, participate in another Research Program or other Service, You may earn points, which can redeemed for various rewards or cash in Our incentive program. You do not have to purchase anything in order to receive points. The points You have earned are personal and You cannot transfer them to anybody else. Your points will be valid and redeemable for a period of twelve (12) months after your account becomes inactive. Any points or incentives not redeemed by You may be revoked by Us.",
            "links": []
          },
          {
            "type": "p",
            "text": "At the beginning of a Survey, other Research Program or other Service, You will receive information about the number of points that You may earn. We do not accept to be liable or responsible in any manner for tax consequences or duties that may occur as a result of points or incentives issued or redeemed. If You breach the Terms You may lose all the points or incentives which You have earned. We do not accept any liability to You in relation to the points You have earned.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "10-policy-on-points-based-incentive-programs"
      },
      {
        "heading": "11. Profile Updates",
        "blocks": [
          {
            "type": "p",
            "text": "Panel Members agree to keep their membership profiles updated. A Panel Member may update, correct, and/or delete information contained in his or her membership profiles by: (a) accessing his or her Panel membership account; or (b) sending an email to the appropriate Panel Member services team for the relevant Panel.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "11-profile-updates"
      },
      {
        "heading": "12. Opt-Out Policy",
        "blocks": [
          {
            "type": "p",
            "text": "Panel Members may opt-out from using any or all Services (including, without limitation, from receiving Survey invitations, newsletters or communications) at any time by: (a) following the unsubscribe procedures described on the relevant Panel Site or related sites or contained in an email received from Us; or (b) by sending an email to Our Panel Member services team by replying to the emails We send You or by using the contact details mentioned on the site where You login to Your Panel Member’s account.",
            "links": []
          },
          {
            "type": "p",
            "text": "We shall use reasonable efforts, as required by law or regulation, to respond to each email request within a reasonable period of time after receipt. Upon termination of Services, a Panel Member’s contact information will be removed from all communication or contact lists relating to the terminated Service(s). Please note that it may take a few days to complete the removal and during such time, You may receive messages from Us which were created or compiled prior to Your opt-out.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "12-opt-out-policy"
      },
      {
        "heading": "13. Links",
        "blocks": [
          {
            "type": "p",
            "text": "In connection with Your use of the Service, You may be able to link or connect to a Third Party Website. Please note that We do not endorse any Third Party Website or products, services, and/or opportunities advertised, offered, through or in connection with such Third Party Website. Please review all policies and terms applicable to such Third Party Websites carefully.",
            "links": []
          }
        ],
        "id": "13-links"
      },
      {
        "heading": "14. Communications with Us",
        "blocks": [
          {
            "type": "p",
            "text": "All communications (excluding Personal Data) and User Content submitted or transmitted by You to Us, by electronic mail or otherwise, or otherwise collected by Us, will be treated as non-confidential and non-proprietary information of Yours, unless You specifically indicate otherwise either prior to, or contemporaneously with, Your submission of or permission to Us to collect such communications and User Content. You agree that any such communications and User Content may be used by Us at Our own discretion.",
            "links": []
          }
        ],
        "id": "14-communications-with-us"
      },
      {
        "heading": "15. Privacy",
        "blocks": [
          {
            "type": "p",
            "text": "When applying for Panel membership, using a Service or otherwise communicating with Us or a Panel Owner, Personal Data pertaining to You may be processed. For information about Our privacy practices and the processing of Your Personal Data, please review the Research Participant Privacy Notice here.",
            "links": [
              {
                "label": "here",
                "href": "https://www.datadiggers-mr.com/privacy-policy/"
              }
            ]
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "15-privacy"
      },
      {
        "heading": "16. Disclaimer",
        "blocks": [
          {
            "type": "p",
            "text": "You expressly agree that Your participation in a Survey, other Research Program and use of the Service and browsing of Our site, a Survey Site, a Panel Site or a Partner Site is at Your sole risk and responsibility. To the fullest extent permitted by law, We, Our Clients, Survey Owners, Panel Owners, Partners, or other third parties, and Our and their respective directors, officers, employees, representatives, agents, third-party content providers and licensors, do not make any warranties, express, implied or statutory, including those of merchantability, fitness for a particular purpose, that participation in a Survey or the use of the Service, Our site, a Survey Site, a Panel Site, or a Partner Site will be uninterrupted or error free. To the fullest extent permitted by law, We, Our Clients, Survey Owners, Panel Owners, Partners, or other third parties, and Our and their respective directors, officers, employees, representatives, agents, third-party content providers and licensors, do not make any warranties, express, implied or statutory, including those of merchantability, fitness for a particular purpose, to the accuracy, reliability, or content of any information, or services provided through a Survey or Our site, a Survey Site, a Panel Site, or a Partner Site, other than as expressly set out in these Terms.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "16-disclaimer"
      },
      {
        "heading": "17. Limitation of Liability",
        "blocks": [
          {
            "type": "p",
            "text": "TO THE EXTENT PERMITTED BY APPLICABLE LAW, WE, SURVEY OWNERS, PANEL OWNERS OR PARTNERS, THIRD PARTIES, OR DIRECTORS, OFFICERS, SHAREHOLDERS, EMPLOYEES, REPRESENTATIVES, CONTRACTORS, SUCCESSORS OR ASSIGNEES SHALL NOT BE LIABLE TO YOU IN ANY RESPECT, INCLUDING WITHOUT LIMITATION, FOR ANY MATTER RELATED TO THESE TERMS, THE SERVICE, OUR SITE, A SURVEY, A PANEL SITE, A PARTNER SITE OR FOR ANY SUBMISSIONS YOU MAKE, OR FOR ANY DIRECT, INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL, RELIANCE, EXEMPLARY OR CONSEQUENTIAL DAMAGES, LOSS OF PROFITS, LOSS OF EXPECTED SAVINGS, OR ANY OTHER NON-DIRECT DAMAGES, WHETHER OR NOT WE HAVE BEEN ADVISED OF THE LIKELIHOOD OR POSSIBILITY OF SUCH DAMAGES.",
            "links": []
          },
          {
            "type": "p",
            "text": "The limitation of liability and the disclaimer in these Terms shall apply regardless of the form of action, whether in contract, warranty, delict, quasi-delict, strict liability, negligence or other tort and shall survive a fundamental breach or breaches or the failure of the essential purpose of contract or the failure of an exclusive remedy.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "17-limitation-of-liability"
      },
      {
        "heading": "18. Indemnification",
        "blocks": [
          {
            "type": "p",
            "text": "You agree to fully and effectively indemnify, defend, and hold Us, Survey Owners, Panel Owners, and Partners, and other related third parties, including directors, officers, shareholders, employees, representatives, contractors, affiliates, successors or assignees, harmless from and against any and all damages, expenses, liabilities and losses of any kind, including legal fees, arising, whether directly or indirectly, from any breach caused by You of the Terms.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "18-indemnification"
      },
      {
        "heading": "19. Changes",
        "blocks": [
          {
            "type": "p",
            "text": "We hereby reserve the right, in Our sole discretion, to make changes to these Terms. We encourage you to review these Terms on an ongoing basis. We will obtain your consent prior to changes that are of such nature that consent is needed or required. For changes that do not require consent, your continued use of, access to and/or participation in the Services does and will constitute your acceptance of these Terms as amended.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "19-changes"
      },
      {
        "heading": "20. Compliance with Applicable Law",
        "blocks": [
          {
            "type": "p",
            "text": "You acknowledge and agree that You shall at all times comply with Applicable Law when You respond to a Survey, participate in another Research Program or otherwise use the Service.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "20-compliance-with-applicable-law"
      },
      {
        "heading": "21. Suspension, Termination and De-Activation",
        "blocks": [
          {
            "type": "p",
            "text": "In addition to any and all other available remedies, We may, without notice, suspend and/or terminate Your use of and access to the Service, or Your membership with a Panel, if You are in breach of these Terms or in the event that You use the Service in an unlawful manner or otherwise act in a manner that is, at Our sole discretion, unacceptable to Us, a Survey Owner, Panel Owner, or a Partner. If We terminate Your right to use the Service and/or if Your Panel membership is terminated: (a) You forfeit all rights, title, and interest in and/or to all unredeemed rewards, incentives, and/or prizes, effective upon termination; (b) Your Panel membership will immediately be canceled; (c) Your access to and use of the Service will immediately cease; and (d) You will not be allowed to participate in any future Surveys offered through the Service.",
            "links": []
          },
          {
            "type": "p",
            "text": "Furthermore, We reserve the right to de-activate Your Panel membership account: (a) if You are no longer an Active Panelist; (b) if We receive a hard bounce or delivery failure notice in Our email communication with Your email account; or (c) if We receive a “mailbox full” reply notice three (3) times in Our email communication to Your email account.",
            "links": []
          },
          {
            "type": "p",
            "text": "In the event of a deactivation, termination by You, or termination by Us, You forfeit any incentives that You have earned.",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "21-suspension-termination-and-de-activation"
      },
      {
        "heading": "22. Severability and Assignment",
        "blocks": [
          {
            "type": "p",
            "text": "If, for any reason whatsoever, any term or provision of these Terms is deemed to be void or unenforceable, such term or provision shall be deemed to be severable from the remainder of these Terms, and the remainder of these Terms shall be construed and interpreted without reference to the unenforceable term.",
            "links": []
          },
          {
            "type": "p",
            "text": "You may not assign these Terms without Our prior written consent, which may be withheld at Our sole discretion. You agree that We may assign these Terms at any time to",
            "links": []
          },
          {
            "type": "p",
            "text": "###",
            "links": []
          }
        ],
        "id": "22-severability-and-assignment"
      },
      {
        "heading": "23. Governing Law, Jurisdiction and Legal Venue",
        "blocks": [
          {
            "type": "p",
            "text": "Any disputes arising out of or in connection with these Terms, including any questions regarding its existence, validity or termination, shall be referred to Bucharest court and governed by and construed in accordance with the laws of Romania, without regard to any choice of law principles (whether those of Romania or any other jurisdiction) that might provide for an application of a different jurisdiction’s laws.",
            "links": []
          }
        ],
        "id": "23-governing-law-jurisdiction-and-legal-venue"
      }
    ]
  },
  "click-draw": {
    "slug": "click-draw",
    "title": "Terms and Conditions Raffle “The Click Draw”",
    "sections": [
      {
        "heading": "Section 1. The raffle organizer",
        "blocks": [
          {
            "type": "p",
            "text": "The raffle is organized by: DataDiggers Market Research S.R.L., the main company, with the head office in Voluntari, Erou Constantin Pritopescu 9A, room no. 5, 2nd floor, Ilfov County, Romania, with the registration number J23/915/2015, VAT ID RO34246710, and checking account no RO97INGB0000999904897665, at ING Bank N.V. Amsterdam, Buzesti, represented legally by Paula Elena Pislaru, the Chief Operating Officer, also referred to as the „Organizer”. The raffle will take place in accordance with the provisions of this Regulation, which is mandatory for all participants. The organizer reserves its right to amend or change the rules, with the obligation to officially announce to the public, through the same manner as before.",
            "links": []
          }
        ],
        "id": "section-1-the-raffle-organizer"
      },
      {
        "heading": "Section 2. Place and duration of the raffle",
        "blocks": [
          {
            "type": "p",
            "text": "\"The Click Draw\" contest will be held exclusively online, starting September 1st, 2025 and continues monthly with no predetermined end date, until terminated by the Organizer. Each “Monthly Period” runs from 00:00 to 23:59 (Europe/Bucharest time, EET/EEST) for the calendar month (e.g., September 1–30, October 1–31, etc.). At the start of each month, all entries reset.",
            "links": []
          }
        ],
        "id": "section-2-place-and-duration-of-the-raffle"
      },
      {
        "heading": "Section 3. Terms and conditions",
        "blocks": [
          {
            "type": "p",
            "text": "The raffle is accessible to everyone, regardless of nationality, residence, race, sex or religion, who comply with the conditions of this Regulation to validate their participation. Hoewever, employees of the Organizer and their first-degree relatives cannot participate. Participation in this raffle requires the fulfillment of the following conditions:",
            "links": []
          },
          {
            "type": "list",
            "items": [
              "Qualifying Surveys: For every survey started by a member that ends with “Screenout” or “Quota Full” or “Survey Closed”, the member receives one unique code = one entry. Completed surveys, or any other statuses except “Screenout” or “Quota Full” or “Survey Closed”, do not generate entries.",
              "Unlimited entries per month: Members may earn one entry per qualifying survey with no monthly cap.",
              "Attempt limit per survey: Each member may attempt a given survey only once.",
              "Code delivery & entry: The unique code is shown in the member’s account and logged automatically. Members are auto-entered; no submission is required.",
              "No reclassification: Entries are assigned based on the survey status at the time it is recorded. Later reclassifications do not add or remove entries. The Organizer may audit and void entries suspected of abuse (including, without limitation, bots/automation, duplicate accounts, or behavior intended to artificially trigger screenouts/quotas/survey closed). Otherwise, failure to comply with the aforementioned rules will result in automatic disqualification of the participant. Participation in this raffle has the value of full acceptance, freely consented and outside of any constraint of the provisions of these Regulations. The right to participate belongs exclusively to the participant who meets the conditions imposed by the Regulation. The right to participate in the raffle is automatically revoked if a person provides false, erroneous or inadequate data or information in addition to personal data. The data provided will allow the participants to be informed of the prizes won and are necessary for the validation of the winners. Participation in this raffle constitutes full and unconditional acceptance of this Regulation."
            ]
          }
        ],
        "id": "section-3-terms-and-conditions"
      },
      {
        "heading": "Section 4. Personal data protection",
        "blocks": [
          {
            "type": "p",
            "text": "According to Regulation (EU) no. 679 from April 27th, 2016 for the protection of individuals with regard to the processing of personal data and the free movement of such data (named \"GDPR\"), applied from May 25th, 2018, MyVoice in relation with Data Diggers Market Research S.R.L, having the quality of an \"Operator\", processes your personal data in good faith and in pursuit of the purposes specified in this policy. By entering this raffle, you agree that MyVoice in relation to Data Diggers Market Research S.R.L will process the data regarding your full name and email address, in case you are among the winners. This information will be processed exclusively for the purpose of this raffle. More information on the processing of personal data, including the rights of data subjects, can be found on the MyVoice website: https://myvoice-surveys.com/panelist/privacyPolicy More information on terms and conditions for panel membership, survey participation and use of services can be found on the MyVoice website: https://myvoice-surveys.com/panelist/terms More information on regarding our cookie policy can be found on the MyVoice website: https://myvoice-surveys.com/panelist/cookie_policy",
            "links": [
              {
                "label": "https://myvoice-surveys.com/panelist/privacyPolicy",
                "href": "https://myvoice-surveys.com/panelist/privacyPolicy"
              },
              {
                "label": "https://myvoice-surveys.com/panelist/terms",
                "href": "https://myvoice-surveys.com/panelist/terms"
              },
              {
                "label": "https://myvoice-surveys.com/panelist/cookie\\_policy",
                "href": "https://myvoice-surveys.com/panelist/cookie_policy"
              }
            ]
          }
        ],
        "id": "section-4-personal-data-protection"
      },
      {
        "heading": "Section 5. The raffle mechanism",
        "blocks": [
          {
            "type": "p",
            "text": "The members of the MyVoice panel will find out about the organization of the Raffle on the MyVoice website, on the social media pages, in the MyVoice newsletter or from other campaign communication channels. Registration is automatic: any member who earns a qualifying entry (see Section 3) during a Monthly Period is entered in the draw for that Monthly Period. Entries only count in the month they were issued and do not carry over after month-end.",
            "links": [
              {
                "label": "MyVoice website",
                "href": "http://www.myvoice-surveys.com/"
              },
              {
                "label": "social media pages",
                "href": "https://linktr.ee/myvoicebyddsocial"
              }
            ]
          }
        ],
        "id": "section-5-the-raffle-mechanism"
      },
      {
        "heading": "Section 6. The prizes",
        "blocks": [
          {
            "type": "p",
            "text": "Monthly, the Organizer awards 11 fixed prizes as follows: 1 prize × 50 EUR/USD 10 prizes × 10 EUR/USD each The total value of the prize is 150 euros (or equivalent in dollars). VAT and all related fees will be borne by the Organizer. Prizes are paid in EUR or USD depending on the member panel, credited to the MyVoice member account. The winners of the prize offered in this raffle do not have the opportunity to receive the cash value of the prize or its exchange with other goods.",
            "links": []
          }
        ],
        "id": "section-6-the-prizes"
      },
      {
        "heading": "Section 7. The nomination of the winner",
        "blocks": [
          {
            "type": "p",
            "text": "For each Monthly Period, winners are selected purely at random from all valid entries using random.org. One prize per person per month (winners selected without replacement). The draw, announcement, and prize crediting for a Monthly Period will occur before the end of the following month (e.g., September draw by October 31).",
            "links": []
          }
        ],
        "id": "section-7-the-nomination-of-the-winner"
      },
      {
        "heading": "Section 8. The notification and the receipt of the prize",
        "blocks": [
          {
            "type": "p",
            "text": "Winners will be notified by email (primary) and may also receive a dashboard message in their MyVoice account. By participating in this raffle, participants agree that, in case of winning, the identity of the winner and the awarded prizes will be publicly announced and/or used for advertising purposes, without other obligations or payments from the Organizer. If the winners do not send the information requested by the Organizer within 72 hours or if they have provided incorrect/incomplete contact data, the prize will be awarded to another participant, through a new draw. To receive the prize, the winners must send the Organizer a copy of the ID card.",
            "links": []
          }
        ],
        "id": "section-8-the-notification-and-the-receipt-of-the-"
      },
      {
        "heading": "Section 9. The end of the raffle",
        "blocks": [
          {
            "type": "p",
            "text": "This raffle continues monthly until terminated. The Organizer may modify, suspend, or terminate the raffle and/or this Regulation through the same channels used for announcements. In case of force majeure or events making continuation impossible or illegal (including applicable sanctions or legal restrictions), the raffle may be suspended/terminated immediately. Changes do not affect entries already earned; any ongoing Monthly Period will be handled as communicated in the notice.",
            "links": []
          }
        ],
        "id": "section-9-the-end-of-the-raffle"
      },
      {
        "heading": "Section 10. Raffle rules",
        "blocks": [
          {
            "type": "p",
            "text": "The regulation is available for free on MyVoice. By participating in this raffle, participants agree to comply with this Regulation. Any changes to this Regulations will be communicated on MyVoice’s social media accounts or on its main website.",
            "links": [
              {
                "label": "website",
                "href": "http://www.myvoice-surveys.com/"
              }
            ]
          }
        ],
        "id": "section-10-raffle-rules"
      },
      {
        "heading": "Section 11. Disputes",
        "blocks": [
          {
            "type": "p",
            "text": "In case of disputes between the Organizer and the participants in the raffle, they will be settled amicably. If it is not possible to resolve the disputes amicably, the involved parties will submit the dispute for settlement to the competent Romanian courts. Completed and signed today: 31.08.2025 DataDiggers Market Research S.R.L. Paula Elena Pislaru Chief Operating Officer",
            "links": []
          }
        ],
        "id": "section-11-disputes"
      }
    ]
  }
};

export const legalSlugs = ["privacy","cookies","terms","click-draw"];
