// Parses the vendored source markdown in content/source/ into committed
// TypeScript modules under src/content/. Run on demand: npm run content

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseFaq } from './parse-faq.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = (name) => readFileSync(join(root, 'content', 'source', name), 'utf8');
const out = (rel, body) => {
  const path = join(root, 'src', 'content', rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body, 'utf8');
  console.log(`wrote src/content/${rel}`);
};

const BANNER = `// Generated by scripts/build-content.mjs from content/source/.
// Do not edit by hand. Edit the markdown and run: npm run content
`;

const { categories } = parseFaq(src('Member FAQs.md'));
out(
  'faq.generated.ts',
  `${BANNER}import type { FaqCategory, FaqItem } from './types';

export const faqCategories: FaqCategory[] = ${JSON.stringify(categories, null, 2)};

export const faqItems: FaqItem[] = faqCategories.flatMap((c) => c.items);
`
);
